### ISSUE TITLE
ArrayIndexOutOfBoundsException when generating training set

### ISSUE THREAD

**Issue by lpalomerol** [ikalatskaya/ISOWN#13]
Hello again, 

sorry for the insistence. My "16:10 issue" is related with the generation of the training set. I am trying to run  generate_training_set dataset and java is breaking with this trace:

`
Reformat files in '/home/idibell/Documentos/pipelines/8.pujana/20180716.pdx.mutect/results/20180725.install.isown.db/2.vcf2' to emaf ...

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at com.Processing.processVcf(Processing.java:119)
        at com.runReformating.main(runReformating.java:39)

Generate training data set for '/home/idibell/Documentos/pipelines/8.pujana/20180716.pdx.mutect/results/20180725.install.isown.db/2.vcf2' ...

Exception in thread "main" java.lang.NullPointerException
        at helper.Headers.<init>(Headers.java:41)
        at main.Generator.getVariant2samples(Generator.java:243)
        at main.Generator.loadVariants(Generator.java:19)
        at main.runGenerator.main(runGenerator.java:47)
`

What i am doing wrong?

My JAVA_HOME variable, btw is "/usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.171-8.b10.el7_5.x86_64"

Regards,
Luis.

**Comment by zhaohongqiangsoliva** [comment]
hi 
I also had the same mistake. How did you solve it?
thanks

**Comment by renyongzhe** [comment]
I also got this error. 
cmd: java -jar ISOWN/bin/REFORMVCF_v1.0.jar -vcfFolder case/ -output case_out.emaf
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at com.Processing.processVcf(Processing.java:119)
	at com.runReformating.main(runReformating.java:39)

Maybe the difference of the vcf format between the demo and my case caused this error. Does the value in some column matter?
Appreciate if anyone can point out this.

**Comment by itamuria** [comment]
I also got the same error.

**Comment by amit21AIT** [comment]
Did anyone find a way to correct this error?

**Comment by slavnycoder** [comment]
any updates?
