### ISSUE TITLE
Error when converting VCF file to emaf

### ISSUE THREAD

**Issue by itamuria** [ikalatskaya/ISOWN#23]
Dear Irina, 

I got an error in the 3rd step when I had to convert VCF files to emaf file. 

I used this command:
`perl ${ISOWN_HOME}/bin/run_isown.pl ./annovar_results ./isown_results/test.output.txt " -trainingSet ${ISOWN_HOME}/training_data/BRCA_100_TrainSet.arff -sanityCheck false -classifier nbc" `

And I got this error:

> Reformat files in '/home/ISOWN/annovar_results' to emaf ...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at com.Processing.processVcf(Processing.java:119)
        at com.runReformating.main(runReformating.java:39)

As I didn't get any information about the error it is difficult to know what can we do. 
I would appreciate any feedback. 

Thanks, 
All the best, 
Ibon

**Comment by amit21AIT** [comment]
@itamuria I am also getting the same error when i tried converting VCF to emaf . Did you find a way to correct it ?

**Comment by itamuria** [comment]
Dear @amit21AIT, 
I am in contact with the authors but they haven't provided any resolutive answer. I will let you know if I solve it.

**Comment by amit21AIT** [comment]
@itamuria  i found a way to correct this error , annovar is using hg19 by default but i used hg38 for alignment so i downloaded the hg38.fa file and used -buildver hg38 parameter in  all 3 lines of annovar_annotation.pl file and again did database annotation and now its running fine . Also check whether your annotated vcf file is proper or not , like in my case one of the column name was '1' so i changed it to 'TUMOR' and its working now no errors. Hope it helps.
Thanks

**Comment by peishimei** [comment]
> @itamuria i found a way to correct this error , annovar is using hg19 by default but i used hg38 for alignment so i downloaded the hg38.fa file and used -buildver hg38 parameter in all 3 lines of annovar_annotation.pl file and again did database annotation and now its running fine . Also check whether your annotated vcf file is proper or not , like in my case one of the column name was '1' so i changed it to 'TUMOR' and its working now no errors. Hope it helps.
> Thanks

Hi
I met the same error. But i use the test vcf in dir ISOWN/training_data/ and it was called in hg19.
did you know the qpipeline_internal means? i met the error like no glibc-2.14, and do not run the qpipeline_internal strep where run database_annotation.pl
Thanks

**Comment by djamgo88** [comment]
any updates?

**Comment by slavnycoder** [comment]
try change /ISOWN/bin/annovar_annotation.pl:35 `-buildver hg19` -> `-buildver hg19_25`

**Comment by zjiang-lji** [comment]
@itamuria, have you received any solution from the authors?

**Comment by zjiang-lji** [comment]
@slavnycoder, I changed `-buildver hg19` to `-buildver hg19_25` in `/ISOWN/bin/annovar_annotation.pl:35`. Then I was prompted to do the following but no commands are working:
```
The gene annotation database <redacted>/ISOWN/bin/../external_tools/annovar/humandb/hg19_25_refGene.txt does not exist.
Please use 'annotate_variation.pl --downdb refGene <redacted>/ISOWN/bin/../external_tools/annovar/humandb -build hg19_25' to download the database.
```
How were you able to annotate with Annovar hg19_25 using
```
perl $cwd/../external_tools/annovar/annotate_variation.pl -geneanno ${outputVCFFile}.temp.convert2annovar -buildver hg19_25 $cwd/../external_tools/annovar/humandb`
```
in `/ISOWN/bin/annovar_annotation.pl`?
